In [1]:
import sys
!{sys.executable} -m pip install lightgbm

Requirement already satisfied: lightgbm in c:\users\hp\anaconda3\lib\site-packages (4.6.0)
Requirement already satisfied: numpy>=1.17.0 in c:\users\hp\anaconda3\lib\site-packages (from lightgbm) (1.26.4)
Requirement already satisfied: scipy in c:\users\hp\anaconda3\lib\site-packages (from lightgbm) (1.13.1)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: C:\Users\HP\anaconda3\python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, r2_score

import joblib

In [5]:
data = pd.read_csv("ag1.csv")

print("Dataset shape:", data.shape)
data.head()

Dataset shape: (1118899, 11)

,Sl no.,District Name,Market Name,Commodity,Variety,Grade,Min Price (Rs./Quintal),Max Price (Rs./Quintal),Modal Price (Rs./Quintal),Price Date,State
0,1,Auraiya,Achalda,Wheat,Dara,FAQ,2350.0,2550.0,2450.0,05 Apr 2025,Uttar Pradesh
1,2,Auraiya,Achalda,Wheat,Dara,FAQ,2400.0,2500.0,2470.0,14 Jun 2025,Uttar Pradesh
2,3,Auraiya,Achalda,Wheat,Dara,FAQ,2400.0,2500.0,2470.0,23 Jun 2025,Uttar Pradesh
3,4,Auraiya,Achalda,Wheat,Dara,FAQ,2400.0,2520.0,2470.0,26 Jun 2025,Uttar Pradesh
4,5,Auraiya,Achalda,Wheat,Dara,FAQ,2400.0,2550.0,2500.0,03 Jun 2025,Uttar Pradesh

In [7]:
data = data.loc[:, ~data.columns.duplicated()]

In [9]:
data.head()

,Sl no.,District Name,Market Name,Commodity,Variety,Grade,Min Price (Rs./Quintal),Max Price (Rs./Quintal),Modal Price (Rs./Quintal),Price Date,State
0,1,Auraiya,Achalda,Wheat,Dara,FAQ,2350.0,2550.0,2450.0,05 Apr 2025,Uttar Pradesh
1,2,Auraiya,Achalda,Wheat,Dara,FAQ,2400.0,2500.0,2470.0,14 Jun 2025,Uttar Pradesh
2,3,Auraiya,Achalda,Wheat,Dara,FAQ,2400.0,2500.0,2470.0,23 Jun 2025,Uttar Pradesh
3,4,Auraiya,Achalda,Wheat,Dara,FAQ,2400.0,2520.0,2470.0,26 Jun 2025,Uttar Pradesh
4,5,Auraiya,Achalda,Wheat,Dara,FAQ,2400.0,2550.0,2500.0,03 Jun 2025,Uttar Pradesh

In [11]:
data.columns = data.columns.str.replace("_x0020_", " ")
data.columns = data.columns.str.strip()

print(data.columns)

Index(['Sl no.', 'District Name', 'Market Name', 'Commodity', 'Variety',
       'Grade', 'Min Price (Rs./Quintal)', 'Max Price (Rs./Quintal)',
       'Modal Price (Rs./Quintal)', 'Price Date', 'State'],
      dtype='object')

In [13]:
data["Price Date"] = pd.to_datetime(
    data["Price Date"],
    errors="coerce",
    dayfirst=True
)

In [15]:
data["week_number"] = data["Price Date"].dt.isocalendar().week
data["month"] = data["Price Date"].dt.month

In [17]:
data = data.rename(columns={
    "Min Price (Rs./Quintal)": "Min Price",
    "Max Price (Rs./Quintal)": "Max Price",
    "Modal Price (Rs./Quintal)": "Modal Price"
})

In [19]:
data = data.dropna(subset=["Min Price","Max Price","Modal Price"])

In [21]:
from sklearn.preprocessing import LabelEncoder

le1 = LabelEncoder()
le2 = LabelEncoder()
le3 = LabelEncoder()

data["Commodity"] = le1.fit_transform(data["Commodity"])
data["District Name"] = le2.fit_transform(data["District Name"])
data["Market Name"] = le3.fit_transform(data["Market Name"])

In [23]:
X = data[
[
"Commodity",
"District Name",
"Market Name",
"Min Price",
"Max Price",
"week_number",
"month"
]
]

y = data["Modal Price"]

In [25]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
X,
y,
test_size=0.2,
random_state=42
)

In [27]:
!pip install lightgbm

Requirement already satisfied: lightgbm in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (4.6.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: numpy>=1.17.0 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from lightgbm) (2.0.0)
Requirement already satisfied: scipy in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from lightgbm) (1.15.2)

In [29]:
from lightgbm import LGBMRegressor

model = LGBMRegressor(
    n_estimators=300,
    learning_rate=0.05,
    random_state=42
)

model.fit(X_train, y_train)

pred = model.predict(X_test)

print("R2 Score:", r2_score(y_test, pred))

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.013520 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1071
[LightGBM] [Info] Number of data points in the train set: 895119, number of used features: 7
[LightGBM] [Info] Start training from score 4366.782457
R2 Score: 0.9906526956764603

In [31]:
from sklearn.metrics import r2_score, mean_absolute_error

pred = model.predict(X_test)

print("MAE:", mean_absolute_error(y_test, pred))
print("R2 Score:", r2_score(y_test, pred))

MAE: 107.37070507330597
R2 Score: 0.9906526956764603

In [33]:
import joblib

joblib.dump(model,"price_prediction_model.pkl")

['price_prediction_model.pkl']